//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int Movie_ID { get; set; }
        public string MovieName { get; set; }
        public string Director { get; set; }
        public string Genre { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public System.DateTime ShownUntil { get; set; }
        public Nullable<int> NumberOfTickets { get; set; }
    }
}
