//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieHall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieHall()
        {
            this.SpecialDeals = new HashSet<SpecialDeal>();
        }
    
        public int MovieHall_ID { get; set; }
        public string HallName { get; set; }
        public int Capacity { get; set; }
        public string ScreeningTime { get; set; }
        public int Cinema_ID { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialDeal> SpecialDeals { get; set; }
    }
}
