//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialDeal
    {
        public int SpecialDeals_ID { get; set; }
        public string SpecialDeals_name { get; set; }
        public int Discount { get; set; }
        public int MovieHalls_ID { get; set; }
    
        public virtual MovieHall MovieHall { get; set; }
    }
}
